# Generated by Django 5.0.2 on 2024-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
            preserve_default=False,
        ),
    ]
